#!/usr/bin/env python3
"""Instalador, upgrade y diagnóstico de Auditor IPs para Linux."""

from __future__ import annotations

import argparse
import hashlib
import ipaddress
import json
import os
import platform
import re
import secrets
import shutil
import socket
import sqlite3
import subprocess
import sys
import tarfile
import tempfile
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

DEFAULT_REPO_URL = "https://github.com/silfius/auditor-ips.git"
DEFAULT_BRANCH = "main"
DEFAULT_TARGET_DIR = ""
DEFAULT_SYSTEM_TARGET_DIR = "/opt/auditor-ips"
DEFAULT_PORT = "9909"
DEFAULT_TLS_DNS = "auditips.local"
DEFAULT_CONTAINER_NAME = "auditor_ips"
MIN_FREE_BYTES = 2 * 1024**3
RECOMMENDED_FREE_BYTES = 5 * 1024**3
SUPPORTED_ARCHES = {"x86_64", "amd64", "aarch64", "arm64"}
GENERATED_COMPOSE_HEADER = "# Generated by Auditor IPs installer. Manual changes are detected during upgrade.\n"


@dataclass
class CommandResult:
    returncode: int
    stdout: str
    stderr: str


@dataclass
class InterfaceCandidate:
    interface: str
    ip: str
    cidr: str
    network: str
    default_route: bool
    virtual: bool
    state: str
    kind: str


@dataclass
class CheckResult:
    name: str
    status: str
    detail: str


def log(message: str = "") -> None:
    print(message, flush=True)


USE_COLOR = sys.stdout.isatty() and not os.environ.get("NO_COLOR")
ANSI = {
    "reset": "\033[0m",
    "title": "\033[1;36m",
    "muted": "\033[2m",
    "info": "\033[36m",
    "ok": "\033[32m",
    "warn": "\033[33m",
    "error": "\033[31m",
    "prompt": "\033[1m",
}


def color(text: str, name: str) -> str:
    if not USE_COLOR:
        return text
    return f"{ANSI.get(name, '')}{text}{ANSI['reset']}"


def section(title: str, description: str = "") -> None:
    log()
    log(color(f"== {title} ==", "title"))
    if description:
        log(color(f"  {description}", "info"))


def note(message: str) -> None:
    log(color(f"  - {message}", "muted"))


def warn(message: str) -> None:
    log(color(f"ADVERTENCIA: {message}", "warn"))


def run_cmd(
    cmd: list[str],
    cwd: Path | None = None,
    check: bool = False,
    capture: bool = True,
    timeout: int | None = None,
) -> CommandResult:
    proc = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
        timeout=timeout,
    )
    result = CommandResult(proc.returncode, proc.stdout or "", proc.stderr or "")
    if check and result.returncode != 0:
        raise RuntimeError(
            "Comando fallido: "
            + " ".join(cmd)
            + f"\nSTDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
        )
    return result


def command_exists(name: str) -> bool:
    return shutil.which(name) is not None


def docker_prefix() -> list[str]:
    return ["sudo", "docker"] if os.getenv("AUDITOR_DOCKER_USE_SUDO") == "1" else ["docker"]


def docker_cmd(*args: str) -> list[str]:
    return docker_prefix() + list(args)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_os_release() -> dict[str, str]:
    path = Path("/etc/os-release")
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if "=" not in raw:
            continue
        key, value = raw.split("=", 1)
        values[key] = value.strip().strip('"')
    return values


def detect_linux_family() -> str:
    data = read_os_release()
    raw = " ".join((data.get("ID", ""), data.get("ID_LIKE", ""), data.get("NAME", ""))).lower()
    if any(token in raw for token in ("debian", "ubuntu", "linuxmint", "raspbian")):
        return "debian"
    if any(token in raw for token in ("arch", "manjaro", "endeavouros")):
        return "arch"
    return "unknown"


def validate_platform() -> list[str]:
    warnings: list[str] = []
    if platform.system().lower() != "linux":
        raise RuntimeError("El instalador del servidor solo soporta Linux.")
    arch = platform.machine().lower()
    if arch not in SUPPORTED_ARCHES:
        raise RuntimeError(f"Arquitectura no certificada: {arch}.")
    if detect_linux_family() == "unknown":
        warnings.append("Distribución no clasificada: las dependencias deben instalarse manualmente.")
    return warnings


def validate_commands() -> None:
    missing = [name for name in ("git", "python3", "curl", "openssl", "ip", "tar", "docker") if not command_exists(name)]
    if missing:
        raise RuntimeError("Faltan comandos requeridos: " + ", ".join(missing) + ". Ejecuta ./installers/linux/install.sh.")
    result = run_cmd(docker_cmd("compose", "version"), capture=True)
    if result.returncode != 0:
        raise RuntimeError("Docker Compose V2 no está disponible. Ejecuta ./installers/linux/install.sh --install-deps.")
    result = run_cmd(docker_cmd("info"), capture=True)
    if result.returncode != 0:
        raise RuntimeError("No se puede acceder al daemon Docker. Revisa permisos o el servicio Docker.")


def ask(prompt: str, default: str = "", assume_yes: bool = False, help_text: str = "") -> str:
    if assume_yes:
        return default
    if help_text:
        note(help_text)
    suffix = f" [{default}]" if default else ""
    value = input(color(f"{prompt}{suffix}: ", "prompt")).strip()
    return value or default


def ask_bool(prompt: str, default: bool, assume_yes: bool = False, help_text: str = "") -> bool:
    if assume_yes:
        return default
    if help_text:
        note(help_text)
    suffix = "S/n" if default else "s/N"
    value = input(color(f"{prompt} [{suffix}]: ", "prompt")).strip().lower()
    if not value:
        return default
    return value in {"s", "si", "sí", "y", "yes"}


def choose(prompt: str, options: list[tuple[str, str]], default_index: int, assume_yes: bool) -> str:
    if not options:
        raise RuntimeError("No hay opciones disponibles.")
    if assume_yes:
        return options[default_index][0]
    for index, (_, label) in enumerate(options, start=1):
        marker = " (recomendado)" if index - 1 == default_index else ""
        log(f"  {index}. {label}{marker}")
    while True:
        raw = input(color(f"{prompt} [{default_index + 1}]: ", "prompt")).strip()
        if not raw:
            return options[default_index][0]
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1][0]
        warn("Selecciona un número válido.")


def confirm(prompt: str, assume_yes: bool) -> bool:
    return ask_bool(prompt, False, assume_yes)


def sanitize_container_name(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip()).strip("._-")
    return cleaned[:128] or DEFAULT_CONTAINER_NAME


def sanitize_instance_id(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", (value or "").strip()).strip("._-")
    return cleaned[:64]


def generate_instance_id(container_name: str) -> str:
    return f"{sanitize_instance_id(container_name) or DEFAULT_CONTAINER_NAME}_{secrets.token_hex(4)}"


def cookie_name_from_instance(instance_id: str) -> str:
    suffix = re.sub(r"[^A-Za-z0-9_]+", "_", instance_id).strip("_")[:48] or secrets.token_hex(4)
    return f"auditor_session_{suffix}"


def is_probably_virtual_interface(name: str) -> bool:
    lowered = name.lower()
    return lowered.startswith(("lo", "docker", "br-", "veth", "virbr", "tun", "tap", "wg", "zt", "tailscale", "macvlan"))


def detect_default_interfaces() -> set[str]:
    result = run_cmd(["ip", "-j", "route", "show", "default"], capture=True)
    if result.returncode != 0:
        return set()
    try:
        rows = json.loads(result.stdout or "[]")
    except json.JSONDecodeError:
        return set()
    return {str(row.get("dev") or "") for row in rows if row.get("dev")}


def detect_ipv4_candidates(include_virtual: bool = True) -> list[InterfaceCandidate]:
    result = run_cmd(["ip", "-j", "-4", "addr", "show"], capture=True)
    if result.returncode != 0:
        return []
    try:
        rows = json.loads(result.stdout or "[]")
    except json.JSONDecodeError:
        return []
    default_ifaces = detect_default_interfaces()
    candidates: list[InterfaceCandidate] = []
    for row in rows:
        name = str(row.get("ifname") or "")
        if name == "lo":
            continue
        virtual = is_probably_virtual_interface(name)
        if virtual and not include_virtual:
            continue
        state = str(row.get("operstate") or "UNKNOWN")
        kind = str((row.get("linkinfo") or {}).get("info_kind") or "physical")
        for info in row.get("addr_info") or []:
            if info.get("family") != "inet" or info.get("scope") != "global":
                continue
            ip = str(info.get("local") or "")
            prefix = int(info.get("prefixlen") or 0)
            try:
                iface = ipaddress.ip_interface(f"{ip}/{prefix}")
            except ValueError:
                continue
            candidates.append(
                InterfaceCandidate(
                    interface=name,
                    ip=str(iface.ip),
                    cidr=str(iface),
                    network=str(iface.network),
                    default_route=name in default_ifaces,
                    virtual=virtual,
                    state=state,
                    kind=kind,
                )
            )
    candidates.sort(key=lambda item: (item.virtual, not item.default_route, item.interface, item.ip))
    return candidates


def choose_interface(args: argparse.Namespace, assume_yes: bool) -> InterfaceCandidate | None:
    candidates = detect_ipv4_candidates(include_virtual=True)
    if not candidates:
        warn("No se han detectado interfaces IPv4 globales.")
        return None
    section("Interfaz y red", "Selecciona la interfaz conectada a la red que quieres auditar.")
    options: list[tuple[str, str]] = []
    default_index = 0
    for index, item in enumerate(candidates):
        if item.default_route and not item.virtual:
            default_index = index
            break
    for item in candidates:
        flags = []
        if item.default_route:
            flags.append("ruta por defecto")
        if item.virtual:
            flags.append("virtual")
        flags.append(item.state.lower())
        options.append((item.interface + "|" + item.ip, f"{item.interface}: {item.ip} · red {item.network} · {', '.join(flags)}"))
    selected = choose("Interfaz", options, default_index, assume_yes)
    iface_name, ip = selected.split("|", 1)
    return next(item for item in candidates if item.interface == iface_name and item.ip == ip)


def validate_port(value: str) -> int:
    try:
        port = int(str(value).strip())
    except ValueError as exc:
        raise RuntimeError("El puerto debe ser numérico.") from exc
    if not 1 <= port <= 65535:
        raise RuntimeError("El puerto debe estar entre 1 y 65535.")
    return port


def port_is_free(port: int) -> bool:
    for family, address in ((socket.AF_INET, "0.0.0.0"), (socket.AF_INET6, "::")):
        try:
            with socket.socket(family, socket.SOCK_STREAM) as sock:
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                sock.bind((address, port))
        except OSError:
            return False
    return True


def find_free_port(start: int) -> int:
    for port in range(max(1024, start), min(65535, start + 1000)):
        if port_is_free(port):
            return port
    raise RuntimeError("No se ha encontrado un puerto libre cercano.")


def validate_cidr(value: str) -> str:
    try:
        network = ipaddress.ip_network(value.strip(), strict=False)
    except ValueError as exc:
        raise RuntimeError(f"CIDR no válido: {value}") from exc
    if network.version != 4:
        raise RuntimeError("La red principal debe ser IPv4 en esta versión.")
    if network.num_addresses > 65536:
        raise RuntimeError("La red es demasiado grande. Usa una red /16 o más pequeña.")
    return str(network)


def validate_ip(value: str, allow_empty: bool = False) -> str:
    value = value.strip()
    if not value and allow_empty:
        return ""
    try:
        return str(ipaddress.ip_address(value))
    except ValueError as exc:
        raise RuntimeError(f"IP no válida: {value}") from exc


def validate_dns_name(value: str) -> str:
    value = value.strip().strip(".")
    if not value:
        return ""
    if len(value) > 253 or not re.fullmatch(r"[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?", value):
        raise RuntimeError(f"Nombre DNS no válido: {value}")
    return value


def default_target_dir(args: argparse.Namespace) -> Path:
    if args.target_dir:
        return Path(args.target_dir).expanduser().resolve()
    if args.system_install:
        return Path(DEFAULT_SYSTEM_TARGET_DIR).resolve()
    cwd = Path.cwd().resolve()
    if (cwd / "app").is_dir() and (cwd / "installers" / "linux" / "install_auditor.py").exists():
        return cwd
    return (Path.home() / "auditor-ips").resolve()


def resolve_host_path(target_dir: Path, configured: str) -> Path:
    path = Path(configured).expanduser()
    return path if path.is_absolute() else (target_dir / path).resolve()


def check_path_writable(path: Path, create: bool = False) -> tuple[bool, str]:
    target = path
    if create:
        try:
            target.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            return False, str(exc)
    probe_parent = target if target.is_dir() else target.parent
    if not probe_parent.exists():
        probe_parent = next((parent for parent in probe_parent.parents if parent.exists()), Path("/"))
    try:
        fd, name = tempfile.mkstemp(prefix=".auditor-write-test-", dir=probe_parent)
        os.close(fd)
        Path(name).unlink(missing_ok=True)
        return True, str(probe_parent)
    except OSError as exc:
        return False, str(exc)


def disk_free_bytes(path: Path) -> int:
    current = path
    while not current.exists() and current != current.parent:
        current = current.parent
    return shutil.disk_usage(current).free


def clean_dns_search_domain(value: str) -> str:
    """Normaliza dominios de búsqueda y descarta raíces, rutas y valores no DNS."""
    item = str(value or "").strip()
    if item in {"", ".", "~", "~."}:
        return ""
    if item.startswith("~"):
        item = item[1:]
    item = item.strip(".")
    if not item:
        return ""
    lowered = item.lower()
    if lowered in {
        "global",
        "link",
        "default",
        "defaultroute",
        "llmnr",
        "mdns",
        "dnssec",
        "dns",
    }:
        return ""
    try:
        ipaddress.ip_address(item)
        return ""
    except ValueError:
        pass
    if not re.fullmatch(r"[A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+)*", item):
        return ""
    if not any(ch.isalpha() for ch in item):
        return ""
    return item


def detect_resolv_conf_dns(path: Path = Path("/etc/resolv.conf")) -> dict[str, list[str]]:
    dns: list[str] = []
    search: list[str] = []
    if not path.exists():
        return {"dns": dns, "search": search}
    for raw in path.read_text(errors="replace").splitlines():
        parts = raw.strip().split()
        if not parts or parts[0].startswith("#"):
            continue
        if parts[0] == "nameserver" and len(parts) > 1:
            try:
                dns.append(str(ipaddress.ip_address(parts[1])))
            except ValueError:
                pass
        elif parts[0] in {"search", "domain"}:
            for value in parts[1:]:
                domain = clean_dns_search_domain(value)
                if domain:
                    search.append(domain)
    return {"dns": list(dict.fromkeys(dns)), "search": list(dict.fromkeys(search))}


def detect_resolvectl_dns() -> dict[str, list[str]]:
    dns: list[str] = []
    search: list[str] = []
    if not command_exists("resolvectl"):
        return {"dns": dns, "search": search}
    for command, target in ((["resolvectl", "dns"], dns), (["resolvectl", "domain"], search)):
        result = run_cmd(command, capture=True)
        if result.returncode != 0:
            continue
        for raw in result.stdout.splitlines():
            payload = raw.split(":", 1)[1] if ":" in raw else raw
            for token in re.split(r"[,\s]+", payload):
                token = token.strip()
                if not token:
                    continue
                if target is dns:
                    try:
                        target.append(str(ipaddress.ip_address(token)))
                    except ValueError:
                        pass
                else:
                    domain = clean_dns_search_domain(token)
                    if domain:
                        target.append(domain)
    return {"dns": list(dict.fromkeys(dns)), "search": list(dict.fromkeys(search))}


def detect_host_dns() -> dict[str, object]:
    dns: list[str] = []
    search: list[str] = []
    sources: list[str] = []
    for name, detector in (("resolvectl", detect_resolvectl_dns), ("/etc/resolv.conf", detect_resolv_conf_dns)):
        try:
            values = detector()
        except Exception as exc:
            warn(f"No se pudo consultar {name}: {exc}")
            continue
        if values["dns"] or values["search"]:
            sources.append(name)
        dns.extend(values["dns"])
        search.extend(values["search"])
    unique_dns = list(dict.fromkeys(dns))
    classified = []
    for value in unique_dns:
        ip = ipaddress.ip_address(value)
        if ip.is_loopback:
            kind = "loopback"
        elif ip.is_private:
            kind = "LAN/privada"
        else:
            kind = "pública"
        classified.append({"value": value, "kind": kind})
    return {"dns": classified, "search": list(dict.fromkeys(search)), "sources": sources}


def recommended_dns(detected: dict[str, object], selected_network: str) -> list[str]:
    network = ipaddress.ip_network(selected_network, strict=False)
    same_network: list[str] = []
    private: list[str] = []
    for item in detected.get("dns") or []:
        value = str(item["value"])
        ip = ipaddress.ip_address(value)
        if ip.is_loopback:
            continue
        if ip in network:
            same_network.append(value)
        elif ip.is_private:
            private.append(value)
    return same_network or private


def csv_values(values: Iterable[str]) -> str:
    return ",".join(dict.fromkeys(value.strip() for value in values if value.strip()))


def read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def render_env(template_text: str, overrides: dict[str, str]) -> str:
    output: list[str] = []
    seen: set[str] = set()
    for line in template_text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            key = stripped.split("=", 1)[0].strip()
            if key in overrides:
                output.append(f"{key}={overrides[key]}")
                seen.add(key)
            else:
                output.append(line)
        else:
            output.append(line)
    for key, value in overrides.items():
        if key not in seen:
            output.append(f"{key}={value}")
    return "\n".join(output).rstrip() + "\n"


def render_compose(template_text: str, config: dict[str, str]) -> str:
    text = template_text
    block: list[str] = []
    for key, yaml_key in (("DOCKER_DNS", "dns"), ("DOCKER_DNS_SEARCH", "dns_search")):
        values = [value.strip() for value in config.get(key, "").split(",") if value.strip()]
        if values:
            block.append(f"    {yaml_key}:")
            block.extend(f"      - {json.dumps(value)}" for value in values)
    if block:
        marker = '    network_mode: "host"\n'
        if marker not in text:
            raise RuntimeError("La plantilla Compose no contiene network_mode: host.")
        text = text.replace(marker, marker + "\n".join(block) + "\n", 1)
    return GENERATED_COMPOSE_HEADER + text.lstrip()


def clone_or_update_repo(repo_url: str, branch: str, target_dir: Path, dry_run: bool) -> None:
    if target_dir.exists() and (target_dir / ".git").exists():
        if dry_run:
            log(f"DRY-RUN git -C {target_dir} fetch/checkout/pull {branch}")
            return
        run_cmd(["git", "fetch", "origin", branch], cwd=target_dir, check=True)
        run_cmd(["git", "checkout", branch], cwd=target_dir, check=True)
        run_cmd(["git", "pull", "--ff-only", "origin", branch], cwd=target_dir, check=True)
        return
    if target_dir.exists() and any(target_dir.iterdir()):
        markers = [target_dir / "app", target_dir / "installers" / "linux" / "env.linux.example", target_dir / "installers" / "linux" / "docker-compose.linux.yml.example"]
        if all(path.exists() for path in markers):
            note("Fuentes existentes sin .git detectadas; se utiliza la carpeta actual.")
            return
        raise RuntimeError(f"La ruta destino no está vacía ni contiene una copia válida: {target_dir}")
    if dry_run:
        log(f"DRY-RUN git clone --branch {branch} {repo_url} {target_dir}")
        return
    target_dir.parent.mkdir(parents=True, exist_ok=True)
    run_cmd(["git", "clone", "--branch", branch, repo_url, str(target_dir)], check=True)


def container_exists(name: str) -> bool:
    result = run_cmd(docker_cmd("ps", "-a", "--format", "{{.Names}}"), capture=True)
    return name in {line.strip() for line in result.stdout.splitlines()}


def perform_preflight(target_dir: Path, requested_port: str | None = None, fresh_install: bool = True) -> list[CheckResult]:
    results: list[CheckResult] = []
    os_data = read_os_release()
    results.append(CheckResult("Sistema", "OK", f"{os_data.get('PRETTY_NAME', platform.platform())} · {platform.machine()}"))
    for command in ("git", "python3", "curl", "openssl", "ip", "tar", "docker"):
        results.append(CheckResult(command, "OK" if command_exists(command) else "ERROR", shutil.which(command) or "no encontrado"))
    compose = run_cmd(docker_cmd("compose", "version"), capture=True)
    results.append(CheckResult("Docker Compose", "OK" if compose.returncode == 0 else "ERROR", (compose.stdout or compose.stderr).strip()[:160]))
    daemon = run_cmd(docker_cmd("info"), capture=True)
    results.append(CheckResult("Daemon Docker", "OK" if daemon.returncode == 0 else "ERROR", "accesible" if daemon.returncode == 0 else daemon.stderr.strip()[:160]))
    writable, detail = check_path_writable(target_dir.parent, create=False)
    results.append(CheckResult("Ruta instalación", "OK" if writable else "ERROR", detail))
    free = disk_free_bytes(target_dir)
    disk_status = "OK" if free >= RECOMMENDED_FREE_BYTES else "WARN" if free >= MIN_FREE_BYTES else "ERROR"
    results.append(CheckResult("Espacio libre", disk_status, f"{free / 1024**3:.1f} GiB"))
    interfaces = detect_ipv4_candidates(include_virtual=True)
    results.append(CheckResult("Interfaces IPv4", "OK" if interfaces else "WARN", f"{len(interfaces)} detectadas"))
    if requested_port:
        try:
            port = validate_port(requested_port)
            free_port = port_is_free(port) if fresh_install else True
            if free_port:
                results.append(CheckResult("Puerto", "OK", f"{port} libre"))
            else:
                suggested = find_free_port(port + 1)
                results.append(CheckResult("Puerto", "WARN", f"{port} ocupado; se propondrá {suggested}"))
        except RuntimeError as exc:
            results.append(CheckResult("Puerto", "ERROR", str(exc)))
    return results


def show_preflight(results: list[CheckResult]) -> None:
    section("Preflight", "Comprobaciones antes de escribir o arrancar la instalación.")
    width = max(len(result.name) for result in results)
    for result in results:
        status_color = "ok" if result.status == "OK" else "warn" if result.status == "WARN" else "error"
        log(f"  {result.name.ljust(width)}  {color(result.status.ljust(5), status_color)}  {result.detail}")


def ensure_preflight_ok(results: list[CheckResult]) -> None:
    errors = [result for result in results if result.status == "ERROR"]
    if errors:
        raise RuntimeError("Preflight bloqueante: " + "; ".join(f"{item.name}: {item.detail}" for item in errors))


def show_effective_config_summary(target_dir: Path, config: dict[str, str]) -> None:
    section("Resumen", "Nada se aplicará hasta confirmar estos valores.")
    rows = [
        ("Destino", str(target_dir)),
        ("Perfil", config.get("INSTALLATION_PROFILE", "")),
        ("Interfaz", config.get("NETWORK_INTERFACE", "")),
        ("IP servidor", config.get("SERVER_IP", "")),
        ("Red a auditar", config.get("SCAN_CIDR", "")),
        ("Puerto", config.get("PORT", "")),
        ("Contenedor", config.get("AUDITOR_CONTAINER_NAME", "")),
        ("TLS DNS", config.get("TLS_CERT_DNS", "")),
        ("TLS IP", config.get("TLS_CERT_IP", "")),
        ("DNS Docker", config.get("DOCKER_DNS", "") or "por defecto"),
        ("DNS search", config.get("DOCKER_DNS_SEARCH", "") or "ninguno"),
        ("Datos", config.get("DATA_DIR", "")),
        ("Exportaciones", config.get("EXPORTS_HOST_DIR", "")),
        ("Backups", config.get("BACKUPS_HOST_DIR", "")),
        ("Diagnóstico", config.get("DIAGNOSTICS_HOST_DIR", "")),
    ]
    width = max(len(key) for key, _ in rows)
    for key, value in rows:
        log(f"  {key.ljust(width)} : {value}")


def build_configuration(target_dir: Path, args: argparse.Namespace) -> dict[str, str]:
    existing = read_env_file(target_dir / ".env")
    profile = args.profile
    if not args.yes and not args.profile_explicit:
        section("Tipo de instalación", "El perfil recomendado evita preguntas técnicas que pueden detectarse con seguridad.")
        profile = choose(
            "Perfil",
            [
                ("recommended", "Recomendado: red, IP, puerto y almacenamiento guiados"),
                ("advanced", "Avanzado: revisar identidad, DNS, cookie y TLS"),
            ],
            0,
            False,
        )

    selected = choose_interface(args, args.yes)
    detected_ip = selected.ip if selected else ""
    detected_network = selected.network if selected else "192.168.1.0/24"
    selected_interface = selected.interface if selected else ""

    section("Acceso HTTPS", "El puerto debe estar libre porque Auditor IPs utiliza la red del host.")
    default_port = args.port or existing.get("PORT") or DEFAULT_PORT
    while True:
        port_raw = ask("Puerto HTTPS", default_port, args.yes)
        port = validate_port(port_raw)
        if port_is_free(port) or (target_dir / ".env").exists():
            break
        suggested = find_free_port(port + 1)
        if args.yes:
            port = suggested
            note(f"Puerto solicitado ocupado; se utilizará {suggested}.")
            break
        warn(f"El puerto {port} está ocupado. Puerto libre sugerido: {suggested}.")
        default_port = str(suggested)

    default_container = args.container_name or DEFAULT_CONTAINER_NAME
    if profile == "advanced":
        container_name = sanitize_container_name(ask("Nombre del contenedor", default_container, args.yes))
    else:
        container_name = sanitize_container_name(default_container)
        note(f"Contenedor generado: {container_name}")
    if container_exists(container_name) and not (target_dir / ".env").exists():
        raise RuntimeError(f"Ya existe un contenedor llamado {container_name}.")

    instance_id = sanitize_instance_id(args.instance_id or existing.get("AUDITOR_INSTANCE_ID", "")) or generate_instance_id(container_name)
    cookie_name = args.session_cookie_name or existing.get("SESSION_COOKIE_NAME", "") or cookie_name_from_instance(instance_id)
    if profile == "advanced":
        instance_id = sanitize_instance_id(ask("Identificador único de instancia", instance_id, args.yes))
        cookie_name = ask("Nombre de cookie de sesión", cookie_name, args.yes)

    section("Red principal", "Confirma la IP del servidor y la red donde están los dispositivos que deseas auditar.")
    server_ip = validate_ip(
        ask(
            "IP del servidor",
            args.server_ip or detected_ip,
            args.yes,
            "Es la IP que utilizarán los equipos de la LAN para abrir Auditor IPs.",
        )
    )
    cidr_default = args.scan_cidr or detected_network
    address_count = ipaddress.ip_network(cidr_default, strict=False).num_addresses
    scan_cidr = validate_cidr(
        ask(
            "Red principal a auditar",
            cidr_default,
            args.yes,
            f"La propuesta contiene {address_count} direcciones.",
        )
    )
    if ipaddress.ip_address(server_ip) not in ipaddress.ip_network(scan_cidr, strict=False):
        warn("La IP del servidor no pertenece a la red seleccionada. Puede ser correcto en un host multirred.")

    if profile == "advanced":
        tls_dns = validate_dns_name(ask("Nombre DNS local para TLS", args.tls_dns, args.yes, "Ejemplo: auditips.local. Puede dejarse vacío."))
        tls_ip = validate_ip(ask("IP incluida en el certificado TLS", args.tls_ip or server_ip, args.yes), allow_empty=True)
    else:
        tls_dns = validate_dns_name(args.tls_dns or DEFAULT_TLS_DNS)
        tls_ip = validate_ip(args.tls_ip or server_ip, allow_empty=True)
        note(f"TLS incluirá IP {tls_ip} y DNS {tls_dns}.")

    detected_dns = detect_host_dns()
    section("DNS para Docker", "Se priorizan DNS LAN. Las públicas normalmente no resuelven nombres internos.")
    for item in detected_dns.get("dns") or []:
        note(f"{item['value']} · {item['kind']}")
    suggested_dns = recommended_dns(detected_dns, scan_cidr)
    suggested_search = list(detected_dns.get("search") or [])
    note("Sugerencia: " + (", ".join(suggested_dns) if suggested_dns else "usar DNS por defecto de Docker"))
    if profile == "advanced":
        docker_dns = ask("DNS Docker, separadas por coma", args.docker_dns or existing.get("DOCKER_DNS", "") or csv_values(suggested_dns), args.yes)
        docker_dns_search = ask("Dominios de búsqueda DNS", args.docker_dns_search or existing.get("DOCKER_DNS_SEARCH", "") or csv_values(suggested_search), args.yes)
    else:
        docker_dns = args.docker_dns or existing.get("DOCKER_DNS", "") or csv_values(suggested_dns)
        docker_dns_search = args.docker_dns_search or existing.get("DOCKER_DNS_SEARCH", "") or csv_values(suggested_search)
        note("DNS seleccionadas: " + (docker_dns or "configuración por defecto de Docker"))

    section("Almacenamiento", "Los datos y backups son persistentes; no se eliminan al reconstruir el contenedor.")
    data_dir = ask("Ruta de datos persistentes", args.data_dir, args.yes, "Incluye base de datos y certificados.")
    backups_dir = ask("Ruta de backups", args.backups_dir, args.yes, "Conviene replicar los backups a otro equipo o volumen.")
    if profile == "advanced":
        exports_dir = ask("Ruta de exportaciones", args.exports_dir, args.yes)
        diagnostics_dir = ask("Ruta de diagnósticos", args.diagnostics_dir, args.yes)
    else:
        exports_dir = args.exports_dir
        diagnostics_dir = args.diagnostics_dir
        note(f"Exportaciones: {exports_dir}")
        note(f"Diagnósticos: {diagnostics_dir}")

    return {
        "AUDITOR_CONTAINER_NAME": container_name,
        "AUDITOR_INSTANCE_ID": instance_id,
        "SESSION_COOKIE_NAME": cookie_name,
        "SESSION_COOKIE_SECURE": "1",
        "SESSION_COOKIE_SAMESITE": "strict",
        "PORT": str(port),
        "DB_PATH": "/data/auditor.db",
        "DATA_DIR": data_dir,
        "EXPORTS_HOST_DIR": exports_dir,
        "BACKUPS_HOST_DIR": backups_dir,
        "DIAGNOSTICS_HOST_DIR": diagnostics_dir,
        "TLS_CERT_IP": tls_ip,
        "TLS_CERT_DNS": tls_dns,
        "SERVER_IP": server_ip,
        "SCAN_CIDR": scan_cidr,
        "NETWORK_INTERFACE": selected_interface,
        "DOCKER_DNS": csv_values(part.strip() for part in docker_dns.split(",")),
        "DOCKER_DNS_SEARCH": csv_values(
            domain
            for domain in (
                clean_dns_search_domain(part)
                for part in docker_dns_search.split(",")
            )
            if domain
        ),
        "SESSION_TTL_HOURS": str(args.session_ttl_hours),
        "SCAN_RETENTION_DAYS": str(args.scan_retention_days),
        "INSTALLATION_PROFILE": profile,
        "PLATFORM_PROFILE": "linux_native",
        "DISCOVERY_MODE": "full",
    }

def write_local_config(target_dir: Path, args: argparse.Namespace, config: dict[str, str]) -> None:
    env_template = target_dir / "installers" / "linux" / "env.linux.example"
    compose_template = target_dir / "installers" / "linux" / "docker-compose.linux.yml.example"
    if not env_template.exists() or not compose_template.exists():
        raise RuntimeError("Faltan installers/linux/env.linux.example o installers/linux/docker-compose.linux.yml.example.")
    for key in ("DATA_DIR", "EXPORTS_HOST_DIR", "BACKUPS_HOST_DIR", "DIAGNOSTICS_HOST_DIR"):
        path = resolve_host_path(target_dir, config[key])
        path.mkdir(parents=True, exist_ok=True)
        writable, detail = check_path_writable(path)
        if not writable:
            raise RuntimeError(f"La ruta {path} no es escribible: {detail}")
    env_path = target_dir / ".env"
    compose_path = target_dir / "docker-compose.yml"
    if env_path.exists() and not args.force_config:
        raise RuntimeError(".env ya existe. Usa --upgrade o --force-config para evitar sobrescribir accidentalmente.")
    env_path.write_text(render_env(env_template.read_text(encoding="utf-8"), config), encoding="utf-8")
    env_path.chmod(0o600)
    compose_path.write_text(render_compose(compose_template.read_text(encoding="utf-8"), config), encoding="utf-8")
    log(f"Escrito {env_path}")
    log(f"Escrito {compose_path}")


def validate_compose(target_dir: Path) -> None:
    result = run_cmd(docker_cmd("compose", "config", "--quiet"), cwd=target_dir, capture=True)
    if result.returncode != 0:
        raise RuntimeError("docker compose config --quiet falló.\n" + result.stdout + result.stderr)
    log(color("docker compose config: OK", "ok"))


def wait_health(target_dir: Path, port: str, attempts: int = 60) -> None:
    url = f"https://127.0.0.1:{port}/api/system/healthz"
    for attempt in range(1, attempts + 1):
        result = run_cmd(["curl", "-kfsS", "--connect-timeout", "2", "--max-time", "8", url], capture=True)
        if result.returncode == 0:
            log(color(f"healthz OK en intento {attempt}", "ok"))
            return
        time.sleep(2)
    ps = run_cmd(docker_cmd("compose", "ps", "-a"), cwd=target_dir, capture=True)
    logs = run_cmd(docker_cmd("compose", "logs", "--no-color", "--tail", "160"), cwd=target_dir, capture=True)
    raise RuntimeError(f"healthz no respondió en {url}.\n\nEstado:\n{ps.stdout}{ps.stderr}\nLogs:\n{logs.stdout}{logs.stderr}")


def validate_tls(target_dir: Path, port: str, expected_ip: str, expected_dns: str) -> None:
    server_name = expected_dns.split(",", 1)[0].strip() if expected_dns else "localhost"
    client = subprocess.run(
        ["openssl", "s_client", "-connect", f"127.0.0.1:{port}", "-servername", server_name],
        input="",
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        cwd=str(target_dir),
    )
    if client.returncode != 0 or "BEGIN CERTIFICATE" not in client.stdout:
        raise RuntimeError("No se pudo obtener el certificado TLS servido.")
    cert = subprocess.run(
        ["openssl", "x509", "-noout", "-ext", "subjectAltName"],
        input=client.stdout,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if cert.returncode != 0:
        raise RuntimeError("No se pudo leer subjectAltName del certificado TLS.")
    expected = {"IP Address:127.0.0.1", "DNS:localhost"}
    if expected_ip:
        expected.add(f"IP Address:{expected_ip}")
    if expected_dns:
        expected.update(
            f"DNS:{item.strip()}"
            for item in expected_dns.split(",")
            if item.strip()
        )
    actual = set(
        re.findall(r"(?:DNS:[^,\s]+|IP Address:[^,\s]+)", cert.stdout)
    )
    missing = sorted(expected - actual)
    unexpected = sorted(actual - expected)
    if missing or unexpected:
        details = []
        if missing:
            details.append("faltan " + ", ".join(missing))
        if unexpected:
            details.append("sobran " + ", ".join(unexpected))
        raise RuntimeError(
            "El conjunto SAN del certificado no coincide exactamente: "
            + "; ".join(details)
        )
    log(color("Certificado TLS y conjunto SAN exacto: OK", "ok"))

def build_and_start(target_dir: Path, no_start: bool, port: str, tls_ip: str = "", tls_dns: str = "") -> None:
    log("Construyendo imagen Docker...")
    run_cmd(docker_cmd("compose", "build"), cwd=target_dir, check=True, capture=False)
    if no_start:
        note("Arranque omitido por --no-start.")
        return
    log("Arrancando Auditor IPs...")
    run_cmd(docker_cmd("compose", "up", "-d"), cwd=target_dir, check=True, capture=False)
    wait_health(target_dir, port)
    validate_tls(target_dir, port, tls_ip, tls_dns)


def write_install_state(target_dir: Path, args: argparse.Namespace, config: dict[str, str]) -> None:
    head_result = run_cmd(["git", "rev-parse", "HEAD"], cwd=target_dir, capture=True)
    compose_path = target_dir / "docker-compose.yml"
    state = {
        "schema_version": 3,
        "platform": "linux_native",
        "installer": "installers/linux/install.sh",
        "env_template": "installers/linux/env.linux.example",
        "compose_template": "installers/linux/docker-compose.linux.yml.example",
        "installed_at": datetime.now(timezone.utc).isoformat(),
        "repo_url": args.repo_url,
        "branch": args.branch,
        "git_head": head_result.stdout.strip() if head_result.returncode == 0 else "",
        "target_dir": str(target_dir),
        "config": {key: value for key, value in config.items() if not any(token in key.lower() for token in ("password", "token", "secret", "webhook", "key"))},
        "generated_compose_sha256": sha256_file(compose_path) if compose_path.exists() else "",
    }
    (target_dir / "install_state.json").write_text(json.dumps(state, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    summary = f"""# Auditor IPs — resumen de instalación

- Fecha UTC: {state['installed_at']}
- Commit: {state['git_head']}
- Ruta: {target_dir}
- Interfaz: {config.get('NETWORK_INTERFACE', '')}
- Red: {config.get('SCAN_CIDR', '')}
- Puerto: {config.get('PORT', '')}
- Datos: {config.get('DATA_DIR', '')}
- Backups: {config.get('BACKUPS_HOST_DIR', '')}

## Acceso

- https://{config.get('SERVER_IP', '127.0.0.1')}:{config.get('PORT', DEFAULT_PORT)}/login

Si no existe un administrador, el asistente web inicial solicitará crearlo.
"""
    (target_dir / "install_summary.md").write_text(summary, encoding="utf-8")


def sqlite_backup(source: Path, destination: Path) -> None:
    if not source.exists():
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    source_conn = sqlite3.connect(f"file:{source}?mode=ro", uri=True, timeout=60)
    destination_conn = sqlite3.connect(destination, timeout=60)
    try:
        source_conn.backup(destination_conn)
        quick_check = destination_conn.execute("PRAGMA quick_check").fetchone()[0]
        if quick_check != "ok":
            raise RuntimeError(f"Backup SQLite inválido: {quick_check}")
    finally:
        destination_conn.close()
        source_conn.close()


def create_upgrade_backup(target_dir: Path, env_values: dict[str, str]) -> Path:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    backup_root = target_dir / "upgrade_backups" / stamp
    backup_root.mkdir(parents=True, exist_ok=False)
    for name in (".env", "docker-compose.yml", "install_state.json", "install_summary.md", "upgrade_state.json", "upgrade_summary.md"):
        source = target_dir / name
        if source.is_file():
            destination = backup_root / name
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
    data_dir = resolve_host_path(target_dir, env_values.get("DATA_DIR", "./data"))
    db_source = data_dir / "auditor.db"
    db_destination = backup_root / "data" / "auditor.db"
    sqlite_backup(db_source, db_destination)
    head = run_cmd(["git", "rev-parse", "HEAD"], cwd=target_dir, capture=True)
    manifest = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "previous_git_head": head.stdout.strip() if head.returncode == 0 else "",
        "source_db": str(db_source),
        "backup_db": str(db_destination) if db_destination.exists() else "",
        "files": [],
    }
    for path in sorted(backup_root.rglob("*")):
        if path.is_file():
            manifest["files"].append({"path": path.relative_to(backup_root).as_posix(), "bytes": path.stat().st_size, "sha256": sha256_file(path)})
    (backup_root / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    log(color(f"Backup de upgrade válido: {backup_root}", "ok"))
    return backup_root


def load_install_state(target_dir: Path) -> dict[str, object]:
    path = target_dir / "install_state.json"
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def reconcile_env(target_dir: Path) -> dict[str, str]:
    env_path = target_dir / ".env"
    template_path = target_dir / "installers" / "linux" / "env.linux.example"
    if not template_path.exists():
        raise RuntimeError("La nueva versión no contiene installers/linux/env.linux.example.")
    existing = read_env_file(env_path)
    rendered = render_env(template_path.read_text(encoding="utf-8"), existing)
    env_path.write_text(rendered, encoding="utf-8")
    env_path.chmod(0o600)
    log(".env reconciliado: valores locales conservados y nuevas variables añadidas.")
    return read_env_file(env_path)


def reconcile_compose(target_dir: Path, env_values: dict[str, str], args: argparse.Namespace) -> None:
    compose_path = target_dir / "docker-compose.yml"
    template_path = target_dir / "installers" / "linux" / "docker-compose.linux.yml.example"
    if not template_path.exists():
        raise RuntimeError("La nueva versión no contiene installers/linux/docker-compose.linux.yml.example.")
    candidate = render_compose(template_path.read_text(encoding="utf-8"), env_values)
    current_hash = sha256_file(compose_path)
    state = load_install_state(target_dir)
    generated_hash = str(state.get("generated_compose_sha256") or "")
    manually_modified = bool(generated_hash and current_hash != generated_hash)
    if manually_modified:
        if args.yes:
            raise RuntimeError("docker-compose.yml contiene cambios manuales. Ejecuta el upgrade interactivo para decidir cómo reconciliarlos.")
        section("Compose modificado", "La definición local contiene cambios manuales.")
        action = choose("Acción", [("keep", "Conservar el Compose actual"), ("replace", "Regenerar desde la nueva plantilla"), ("cancel", "Cancelar upgrade")], 0, False)
        if action == "cancel":
            raise RuntimeError("Upgrade cancelado por cambios manuales en Compose.")
        if action == "keep":
            warn("Se conserva Compose actual. Revisa cambios de la nueva plantilla.")
            return
    compose_path.write_text(candidate, encoding="utf-8")
    log("docker-compose.yml reconciliado con la nueva plantilla.")


def run_upgrade(args: argparse.Namespace, target_dir: Path) -> int:
    section("Upgrade guiado", "Crea backup consistente, actualiza código y revierte si falla la validación.")
    if not (target_dir / ".git").exists() or not (target_dir / ".env").exists() or not (target_dir / "docker-compose.yml").exists():
        raise RuntimeError("--upgrade requiere una instalación Git con .env y docker-compose.yml.")
    env_values = read_env_file(target_dir / ".env")
    port = env_values.get("PORT", DEFAULT_PORT)
    if not args.yes and not confirm("Continuar con el upgrade", False):
        return 1
    backup_dir = create_upgrade_backup(target_dir, env_values)
    previous_head = run_cmd(["git", "rev-parse", "HEAD"], cwd=target_dir, check=True).stdout.strip()
    try:
        clone_or_update_repo(args.repo_url, args.branch, target_dir, args.dry_run)
        if args.dry_run:
            return 0
        env_values = reconcile_env(target_dir)
        port = env_values.get("PORT", DEFAULT_PORT)
        reconcile_compose(target_dir, env_values, args)
        validate_compose(target_dir)
        if not args.no_build:
            build_and_start(target_dir, args.no_start, port, env_values.get("TLS_CERT_IP", ""), env_values.get("TLS_CERT_DNS", ""))
        new_head = run_cmd(["git", "rev-parse", "HEAD"], cwd=target_dir, check=True).stdout.strip()
        state = {
            "upgraded_at": datetime.now(timezone.utc).isoformat(),
            "previous_git_head": previous_head,
            "new_git_head": new_head,
            "backup_dir": str(backup_dir),
            "health_validated": not args.no_start,
        }
        (target_dir / "upgrade_state.json").write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")
        (target_dir / "upgrade_summary.md").write_text(f"# Upgrade completado\n\n- Anterior: `{previous_head}`\n- Nuevo: `{new_head}`\n- Backup: `{backup_dir}`\n", encoding="utf-8")
        write_install_state(target_dir, args, env_values)
        log(color("Upgrade completado.", "ok"))
        return 0
    except Exception:
        warn("El upgrade no se ha validado. El backup se conserva para rollback.")
        raise


def latest_upgrade_backup(target_dir: Path) -> Path:
    root = target_dir / "upgrade_backups"
    candidates = sorted(path for path in root.glob("*") if path.is_dir()) if root.exists() else []
    if not candidates:
        raise RuntimeError("No hay backups de upgrade disponibles.")
    return candidates[-1]


def sqlite_quick_check(path: Path) -> str:
    if not path.is_file():
        raise RuntimeError(f"No existe la base SQLite: {path}")
    connection = sqlite3.connect(f"file:{path}?mode=ro", uri=True, timeout=60)
    try:
        row = connection.execute("PRAGMA quick_check").fetchone()
    finally:
        connection.close()
    result = str(row[0] if row else "")
    if result != "ok":
        raise RuntimeError(f"SQLite quick_check falló para {path}: {result}")
    return result


def validate_upgrade_backup(backup_dir: Path) -> dict[str, object]:
    manifest_path = backup_dir / "manifest.json"
    if not manifest_path.is_file():
        raise RuntimeError(f"El backup no contiene manifest.json: {backup_dir}")
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        raise RuntimeError(f"Manifest de backup inválido: {exc}") from exc
    if not isinstance(manifest, dict):
        raise RuntimeError("El manifest del backup no es un objeto JSON.")

    files = manifest.get("files")
    if not isinstance(files, list):
        raise RuntimeError("El manifest del backup no contiene una lista files válida.")

    backup_root = backup_dir.resolve()
    for item in files:
        if not isinstance(item, dict):
            raise RuntimeError("Entrada no válida en manifest.files.")
        relative = str(item.get("path") or "")
        if not relative:
            raise RuntimeError("Entrada de backup sin path.")
        candidate = (backup_dir / relative).resolve()
        if candidate != backup_root and backup_root not in candidate.parents:
            raise RuntimeError(f"Ruta insegura en manifest: {relative}")
        if not candidate.is_file():
            raise RuntimeError(f"Fichero ausente en backup: {relative}")
        expected_bytes = int(item.get("bytes") or -1)
        if candidate.stat().st_size != expected_bytes:
            raise RuntimeError(f"Tamaño incorrecto en backup: {relative}")
        expected_sha = str(item.get("sha256") or "")
        if not re.fullmatch(r"[0-9a-f]{64}", expected_sha):
            raise RuntimeError(f"SHA-256 inválido en manifest: {relative}")
        if sha256_file(candidate) != expected_sha:
            raise RuntimeError(f"SHA-256 no coincide en backup: {relative}")

    previous_head = str(manifest.get("previous_git_head") or "")
    if previous_head and not re.fullmatch(r"[0-9a-f]{40}", previous_head):
        raise RuntimeError("previous_git_head no es un commit SHA-1 válido.")

    backup_db = backup_dir / "data" / "auditor.db"
    if backup_db.exists():
        sqlite_quick_check(backup_db)

    log(color(f"Backup de rollback validado: {backup_dir}", "ok"))
    return manifest


def restore_sqlite_atomic(backup_db: Path, data_dir: Path) -> str:
    data_dir.mkdir(parents=True, exist_ok=True)
    target_db = data_dir / "auditor.db"
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=".auditor.db.rollback-",
        suffix=".tmp",
        dir=data_dir,
    )
    os.close(descriptor)
    temporary_db = Path(temporary_name)
    try:
        shutil.copyfile(backup_db, temporary_db)
        temporary_db.chmod(0o664)
        sqlite_quick_check(temporary_db)
        for suffix in ("-wal", "-shm"):
            (data_dir / f"auditor.db{suffix}").unlink(missing_ok=True)
        os.replace(temporary_db, target_db)
        sqlite_quick_check(target_db)
        return "host_atomic"
    finally:
        temporary_db.unlink(missing_ok=True)


def compose_service_name(target_dir: Path) -> str:
    result = run_cmd(
        docker_cmd("compose", "config", "--services"),
        cwd=target_dir,
        check=True,
    )
    services = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    if "auditor_ips" in services:
        return "auditor_ips"
    if len(services) == 1:
        return services[0]
    raise RuntimeError(
        "No se puede determinar de forma inequívoca el servicio de Auditor IPs."
    )


def restore_sqlite_with_docker(
    target_dir: Path,
    backup_db: Path,
    data_dir: Path,
) -> str:
    service = compose_service_name(target_dir)
    backup_mount = str(backup_db.parent.resolve())
    script = (
        "set -eu; "
        "test -f /rollback-source/auditor.db; "
        "rm -f /data/auditor.db /data/auditor.db-wal /data/auditor.db-shm; "
        "cp /rollback-source/auditor.db /data/auditor.db; "
        "chmod 0664 /data/auditor.db"
    )
    run_cmd(
        docker_cmd(
            "compose",
            "run",
            "--rm",
            "--no-deps",
            "--entrypoint",
            "/bin/sh",
            "-v",
            f"{backup_mount}:/rollback-source:ro",
            service,
            "-c",
            script,
        ),
        cwd=target_dir,
        check=True,
        capture=False,
    )
    sqlite_quick_check(data_dir / "auditor.db")
    return "docker_helper"


def restore_sqlite_database(
    target_dir: Path,
    backup_db: Path,
    data_dir: Path,
) -> str:
    try:
        method = restore_sqlite_atomic(backup_db, data_dir)
    except (OSError, PermissionError) as exc:
        warn(
            "La restauración directa no pudo sustituir la base "
            f"({exc}). Se utilizará un contenedor auxiliar."
        )
        method = restore_sqlite_with_docker(
            target_dir,
            backup_db,
            data_dir,
        )
    log(color(f"Base SQLite restaurada mediante {method}.", "ok"))
    return method


def restore_backup_files(target_dir: Path, backup_dir: Path) -> str:
    for name in (
        ".env",
        "docker-compose.yml",
        "install_state.json",
        "install_summary.md",
    ):
        source = backup_dir / name
        if source.is_file():
            shutil.copy2(source, target_dir / name)

    env_values = read_env_file(target_dir / ".env")
    data_dir = resolve_host_path(
        target_dir,
        env_values.get("DATA_DIR", "./data"),
    )
    backup_db = backup_dir / "data" / "auditor.db"
    if not backup_db.exists():
        return "no_database"
    return restore_sqlite_database(
        target_dir,
        backup_db,
        data_dir,
    )


def run_rollback(args: argparse.Namespace, target_dir: Path) -> int:
    section(
        "Rollback",
        "Restaura código, configuración y base de datos del último upgrade.",
    )
    backup_dir = latest_upgrade_backup(target_dir)
    manifest = validate_upgrade_backup(backup_dir)
    previous_head = str(manifest.get("previous_git_head") or "")
    note(f"Backup: {backup_dir}")
    note(f"Commit anterior: {previous_head}")
    if not args.yes and not confirm(
        "Detener Auditor IPs y restaurar este backup",
        False,
    ):
        return 1

    run_cmd(
        docker_cmd("compose", "down"),
        cwd=target_dir,
        check=True,
        capture=False,
    )

    # Se restaura primero la configuración y la DB. Así, un fallo de
    # permisos no modifica todavía el commit de la instalación.
    restore_method = restore_backup_files(target_dir, backup_dir)

    if previous_head:
        run_cmd(
            ["git", "checkout", args.branch],
            cwd=target_dir,
            check=True,
        )
        run_cmd(
            ["git", "reset", "--hard", previous_head],
            cwd=target_dir,
            check=True,
            capture=False,
        )

    env_values = read_env_file(target_dir / ".env")
    validate_compose(target_dir)
    build_and_start(
        target_dir,
        False,
        env_values.get("PORT", DEFAULT_PORT),
        env_values.get("TLS_CERT_IP", ""),
        env_values.get("TLS_CERT_DNS", ""),
    )
    log(color(f"Rollback completado ({restore_method}).", "ok"))
    return 0


SENSITIVE_KEY_PATTERN = re.compile(
    r"(?:password|passwd|secret|token|webhook|api[_-]?key|apikey|authorization|private[_-]?key)",
    re.IGNORECASE,
)


def is_sensitive_key(key: str) -> bool:
    return bool(SENSITIVE_KEY_PATTERN.search(str(key or "")))


def secret_values_from_env(values: dict[str, str]) -> list[str]:
    secrets_found = {
        str(value)
        for key, value in values.items()
        if is_sensitive_key(key) and str(value)
    }
    return sorted(secrets_found, key=len, reverse=True)


def redact_text(text: str, secret_values: Iterable[str] = ()) -> str:
    output = str(text or "")
    for value in sorted({str(item) for item in secret_values if str(item)}, key=len, reverse=True):
        output = output.replace(value, "[REDACTED]")

    output = re.sub(
        r"(?im)\b(authorization\s*:\s*)(?:bearer\s+)?[^\s\"']+",
        r"\1[REDACTED]",
        output,
    )
    output = re.sub(
        r"(?im)\b(password|passwd|secret|token|webhook|api[_-]?key|apikey|private[_-]?key)"
        r"(\s*[:=]\s*)([^\s,;]+)",
        r"\1\2[REDACTED]",
        output,
    )
    output = re.sub(
        r"(?i)https://(?:discord(?:app)?\.com/api/webhooks|hooks\.slack\.com/services)/[^\s\"']+",
        "[REDACTED_WEBHOOK_URL]",
        output,
    )
    return output


def redact_env(path: Path) -> str:
    if not path.exists():
        return "MISSING\n"
    output = []
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if "=" not in raw or raw.lstrip().startswith("#"):
            output.append(raw)
            continue
        key, value = raw.split("=", 1)
        if is_sensitive_key(key):
            value = "[REDACTED]" if value else ""
        output.append(f"{key}={value}")
    return "\n".join(output) + "\n"


def run_diagnose(args: argparse.Namespace, target_dir: Path) -> int:
    section("Diagnóstico", "Genera un paquete técnico redactado, sin base de datos ni secretos.")
    env_values = read_env_file(target_dir / ".env")
    secret_values = secret_values_from_env(env_values)
    diagnostics_dir = resolve_host_path(
        target_dir,
        env_values.get("DIAGNOSTICS_HOST_DIR", args.diagnostics_dir),
    )
    diagnostics_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    work = Path(tempfile.mkdtemp(prefix="auditor-diagnose-"))
    try:
        (work / "system.txt").write_text(
            platform.platform()
            + "\n"
            + json.dumps(read_os_release(), indent=2)
            + "\n",
            encoding="utf-8",
        )
        (work / "env_redacted.txt").write_text(
            redact_env(target_dir / ".env"),
            encoding="utf-8",
        )
        commands = {
            "docker_version.txt": docker_cmd("version"),
            "compose_version.txt": docker_cmd("compose", "version"),
            "docker_info.txt": docker_cmd("info"),
            "compose_ps.txt": docker_cmd("compose", "ps", "-a"),
            "compose_config.txt": docker_cmd("compose", "config", "--no-interpolate"),
            "compose_logs.txt": docker_cmd("compose", "logs", "--no-color", "--tail", "300"),
            "ip_addr.txt": ["ip", "-j", "addr"],
            "ip_route.txt": ["ip", "-j", "route"],
            "disk.txt": ["df", "-h", str(target_dir)],
        }
        for filename, command in commands.items():
            result = run_cmd(command, cwd=target_dir, capture=True)
            content = (
                f"RC={result.returncode}\n"
                f"{result.stdout}\n"
                f"{result.stderr}"
            )
            (work / filename).write_text(
                redact_text(content, secret_values),
                encoding="utf-8",
            )

        port = env_values.get("PORT", DEFAULT_PORT)
        health = run_cmd(
            [
                "curl",
                "-k",
                "-sS",
                "-D",
                "-",
                "--max-time",
                "10",
                f"https://127.0.0.1:{port}/api/system/healthz",
            ],
            capture=True,
        )
        health_content = (
            f"RC={health.returncode}\n"
            f"{health.stdout}\n"
            f"{health.stderr}"
        )
        (work / "healthz.txt").write_text(
            redact_text(health_content, secret_values),
            encoding="utf-8",
        )

        leaks = []
        for path in sorted(work.rglob("*")):
            if not path.is_file():
                continue
            content = path.read_text(encoding="utf-8", errors="replace")
            for secret in secret_values:
                if secret and secret in content:
                    leaks.append(f"{path.name}:{sha256_file(path)}")
        if leaks:
            raise RuntimeError(
                "El diagnóstico contiene valores sensibles sin redactar: "
                + ", ".join(leaks)
            )

        archive = diagnostics_dir / f"auditor-ips-diagnostic-{stamp}.tar.gz"
        with tarfile.open(archive, "w:gz") as tf:
            tf.add(work, arcname="diagnostic")
        log(color(f"Diagnóstico generado y verificado: {archive}", "ok"))
        return 0
    finally:
        shutil.rmtree(work, ignore_errors=True)


def run_uninstall(args: argparse.Namespace, target_dir: Path) -> int:
    section("Desinstalación", "Puedes retirar el runtime conservando datos o realizar una eliminación completa.")
    mode = args.uninstall_mode
    if not args.yes and not args.uninstall_mode_explicit:
        mode = choose("Modo", [("runtime", "Quitar contenedor e imagen; conservar código y datos"), ("keep-data", "Quitar runtime y código; conservar datos"), ("full", "Eliminar runtime, código y datos")], 0, False)
    env_values = read_env_file(target_dir / ".env")
    data_dir = resolve_host_path(target_dir, env_values.get("DATA_DIR", "./data"))
    if not args.yes and not confirm(f"Confirmar desinstalación modo {mode}", False):
        return 1
    run_cmd(docker_cmd("compose", "down", "--remove-orphans"), cwd=target_dir, capture=False)
    if mode == "runtime":
        log(color("Runtime eliminado; código y datos conservados.", "ok"))
        return 0
    if mode == "keep-data":
        backup_target = target_dir.parent / f"{target_dir.name}-data-preserved-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        if data_dir.exists():
            shutil.move(str(data_dir), str(backup_target))
        shutil.rmtree(target_dir)
        log(color(f"Código eliminado. Datos conservados en {backup_target}", "ok"))
        return 0
    if mode == "full":
        if not args.yes:
            phrase = input("Escribe ELIMINAR TODO para confirmar: ").strip()
            if phrase != "ELIMINAR TODO":
                raise RuntimeError("Confirmación completa no recibida.")
        if data_dir.exists() and target_dir not in data_dir.parents and data_dir != target_dir:
            shutil.rmtree(data_dir)
        shutil.rmtree(target_dir)
        log(color("Instalación eliminada completamente.", "ok"))
        return 0
    raise RuntimeError(f"Modo de desinstalación no válido: {mode}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Asistente de instalación, upgrade y diagnóstico de Auditor IPs.")
    parser.add_argument("--repo-url", default=DEFAULT_REPO_URL)
    parser.add_argument("--branch", default=DEFAULT_BRANCH)
    parser.add_argument("--target-dir", default=DEFAULT_TARGET_DIR)
    parser.add_argument("--system-install", action="store_true")
    parser.add_argument("--profile", choices=("recommended", "advanced"), default="recommended")
    parser.add_argument("--port", default=DEFAULT_PORT)
    parser.add_argument("--container-name", default=DEFAULT_CONTAINER_NAME)
    parser.add_argument("--instance-id", default="")
    parser.add_argument("--session-cookie-name", default="")
    parser.add_argument("--tls-dns", default=DEFAULT_TLS_DNS)
    parser.add_argument("--tls-ip", default="")
    parser.add_argument("--server-ip", default="")
    parser.add_argument("--scan-cidr", default="")
    parser.add_argument("--docker-dns", default="")
    parser.add_argument("--docker-dns-search", default="")
    parser.add_argument("--data-dir", default="./data")
    parser.add_argument("--exports-dir", default="./exports")
    parser.add_argument("--backups-dir", default="./data/backups")
    parser.add_argument("--diagnostics-dir", default="./diagnostics")
    parser.add_argument("--session-ttl-hours", type=int, default=8)
    parser.add_argument("--scan-retention-days", type=int, default=14)
    parser.add_argument("--yes", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--check-only", action="store_true")
    parser.add_argument("--no-start", action="store_true")
    parser.add_argument("--no-build", action="store_true")
    parser.add_argument("--force-config", action="store_true")
    parser.add_argument("--upgrade", action="store_true")
    parser.add_argument("--rollback", action="store_true")
    parser.add_argument("--diagnose", action="store_true")
    parser.add_argument("--uninstall", action="store_true")
    parser.add_argument("--uninstall-mode", choices=("runtime", "keep-data", "full"), default="runtime")
    args = parser.parse_args()
    args.profile_explicit = "--profile" in sys.argv
    args.uninstall_mode_explicit = "--uninstall-mode" in sys.argv
    return args


def main() -> int:
    args = parse_args()
    target_dir = default_target_dir(args)
    section("Auditor IPs — asistente del servidor", "Instalación guiada y explicada para Linux.")
    note(f"Repositorio: {args.repo_url}")
    note(f"Destino: {target_dir}")
    try:
        warnings = validate_platform()
        validate_commands()
        for item in warnings:
            warn(item)
        if args.diagnose:
            return run_diagnose(args, target_dir)
        if args.rollback:
            return run_rollback(args, target_dir)
        if args.uninstall:
            return run_uninstall(args, target_dir)
        if args.upgrade:
            return run_upgrade(args, target_dir)

        preflight = perform_preflight(target_dir, args.port, fresh_install=not (target_dir / ".env").exists())
        show_preflight(preflight)
        ensure_preflight_ok(preflight)
        if args.check_only:
            log(color("check-only OK", "ok"))
            return 0

        clone_or_update_repo(args.repo_url, args.branch, target_dir, args.dry_run)
        config = build_configuration(target_dir, args)
        show_effective_config_summary(target_dir, config)
        if args.dry_run:
            if not args.yes and not ask_bool("¿El resumen propuesto es correcto?", True, False, "No se escribirá ningún fichero en modo dry-run."):
                return 1
            log(color("dry-run OK: no se ha modificado el sistema.", "ok"))
            return 0
        if not args.yes and not confirm("Aplicar esta configuración", False):
            return 1
        write_local_config(target_dir, args, config)
        validate_compose(target_dir)
        do_build = not args.no_build
        do_start = not args.no_start
        if not args.yes and do_build:
            do_build = ask_bool("Construir la imagen ahora", True, False)
        if not args.yes and do_build and do_start:
            do_start = ask_bool("Arrancar y validar Auditor IPs ahora", True, False)
        if do_build:
            build_and_start(target_dir, not do_start, config["PORT"], config["TLS_CERT_IP"], config["TLS_CERT_DNS"])
        write_install_state(target_dir, args, config)
        log()
        log(color("Instalación validada correctamente.", "ok"))
        log(color(f"Abre https://{config['SERVER_IP']}:{config['PORT']}/login", "ok"))
        log("El primer administrador se crea en el asistente web inicial.")
        return 0
    except Exception as exc:
        log(color(f"ERROR: {exc}", "error"))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
